[platformio]
default_envs = rs485_test_com3
build_dir = C:/pio_build/fyl/rs485_autodir_test

[env]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
monitor_eol = LF
monitor_echo = yes
monitor_encoding = utf-8
build_flags =
  -DCORE_DEBUG_LEVEL=0

[env:rs485_test_com3]
extends = env
build_flags =
  ${env.build_flags}
  -DNODE_ID=3
  -DTARGET_ID=4
  -DAUTO_PING_ENABLED=1
upload_speed = 921600
upload_port = COM3
monitor_port = COM3

[env:rs485_test_com4]
extends = env
build_flags =
  ${env.build_flags}
  -DNODE_ID=4
  -DTARGET_ID=3
  -DAUTO_PING_ENABLED=0
upload_speed = 921600
upload_port = COM4
monitor_port = COM4
