[platformio]
default_envs = conveyor_control_com10
build_dir = C:/pio_build/fyl/conveyor_control_com10

[env:conveyor_control_com10]
platform = espressif32
board = esp32dev
framework = arduino
build_flags =
  -DCORE_DEBUG_LEVEL=0
  -DDEVICE_ROLE_CONVEYOR
upload_speed = 921600
monitor_speed = 115200
monitor_eol = LF
monitor_echo = yes
monitor_encoding = utf-8
upload_port = COM10
monitor_port = COM10
